# Generated by Django 3.0.3 on 2020-03-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='anonymous', max_length=50)),
            ],
            options={
                'verbose_name': 'USER',
                'verbose_name_plural': 'USERs',
            },
        ),
        migrations.CreateModel(
            name='CHAT_MESSAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.CharField(max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom_app.USER')),
            ],
            options={
                'verbose_name': 'chatMessage',
                'verbose_name_plural': 'chatMessages',
            },
        ),
    ]
